### ISSUE TITLE
migrate nuvlabox resources

### ISSUE THREAD

**Issue by loomis** [nuvla/nuvla#20]
Concerning the NuvlaBox resources, the current resources need to be migrated and updated to conform to the parameter naming conventions with Nuvla. This also implies updates to the registration code, as well as adaptations if the registration workflow changes (e.g. adding the extra validation step for Kudelski). The major change will be to have versioned schemas for the nuvlabox-record so that multiple versions of the NuvlaBox software can be supported simultaneously.

**Comment by cjdcordeiro** [comment]
maybe also include a `download` action to the nuvlabox-record, which creates the actual resource and returns the compose-file for installing the NuvlaBox. This compose file should have an environment variable set (`NUVLABOX_ID`) to match the nuvlabox-record id

**Comment by loomis** [comment]
All resources have been migrated and the initial full lifecycle is working.
