### ISSUE TITLE
create NB update action

### ISSUE THREAD

**Issue by cjdcordeiro** [nuvla/nuvla#44]
requires:
 - [x] add persistency to critical environment variables NUVLA_ENDPOINT and NUVLA_ENDPOINT_INSECURE
 - [x] NB agent to add Docker Compose project name and installation compose files to NB status
 - [x] create Nuvla Job to remotely trigger the update of the NB engine, based on the desired NB version (TBD whether this is done remotely or with an auxiliary container deployment. The latter is more solid even though not as clean)

fixes https://github.com/nuvlabox/agent/issues/50
fixes https://github.com/nuvla/api-server/issues/418
fixes https://github.com/nuvlabox/agent/issues/51
fixes https://github.com/nuvla/job-engine/issues/136
fixes https://github.com/nuvlabox/nuvlabox/issues/14
closes https://github.com/nuvlabox/agent/issues/52

**Comment by 0xbase12** [comment]
@cjdcordeiro this ticket should be closed?

**Comment by cjdcordeiro** [comment]
it will be close via the PR Nb update nuvla/job-engine#140
