### ISSUE TITLE
Revoke ssh key from NB fails

### ISSUE THREAD

**Issue by mebster** [nuvla/nuvla#51]
Here' the error:
`NuvlaError-Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nuvla/api/api.py", line 403, in _cimi_request
    response.raise_for_status()
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://api:8200/api/nuvlabox/ba7194d0-1515-477a-ba4c-0322f95fb5ce/commission

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/nuvla/job/executor.py", line 71, in _process_jobs
    return_code = action_instance.do_work()
  File "/usr/local/lib/python3.9/site-packages/nuvla/job/actions/nuvlabox_revoke_ssh_key.py", line 55, in do_work
    return self.revoke_ssh_key()
  File "/usr/local/lib/python3.9/site-packages/nuvla/job/actions/nuvlabox_revoke_ssh_key.py", line 45, in revoke_ssh_key
    connector.commission({"ssh-keys": update_payload})
  File "/usr/local/lib/python3.9/site-packages/nuvla/connector/nuvlabox_connector.py", line 297, in commission
    self.api.operation(self.nuvlabox_resource, "commission", data=payload)
  File "/usr/local/lib/python3.9/site-packages/nuvla/api/api.py", line 569, in operation
    resp_json = self._cimi_post(operation_href, json=data)
  File "/usr/local/lib/python3.9/site-packages/nuvla/api/api.py", line 426, in _cimi_post
    return self._cimi_request('POST', uri, params=params, json=json, data=data)
  File "/usr/local/lib/python3.9/site-packages/nuvla/api/api.py", line 416, in _cimi_request
    raise NuvlaError(message, response)
nuvla.api.api.NuvlaError: resource does not satisfy defined schema:
-- Spec failed --------------------

  {:description ...,
   :capabilities ...,
   :tags ...,
   :refresh-interval ...,
   :updated ...,
   :name ...,
   :credential-api-key ...,
   :created ...,
   :state ...,
   :vpn-server-id ...,
   :updated-by ...,
   :infrastructure-service-group ...,
   :created-by ...,
   :id ...,
   :resource-type ...,
   :acl ...,
   :ssh-keys [[:ssh-keys
               ["credential/8421f9c2-06c3-4957-931c-3223d3016c98"
                "credential/a474e47b-ee59-4575-b226-75a3f5860b55"
                "credential/83d2df8f-3424-49e5-b7ff-1c26ec86c9fe"
                "credential/acb596d8-53a4-42d7-8d32-96cc7c8196ac"
                "credential/1d3cf634-328a-44bc-b5cc-fa3110a9822a"]]],
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   :nuvlabox-status ...,
   :version ...,
   :owner ...}

should satisfy

  string?

-- Relevant specs -------

:sixsq.nuvla.server.resources.spec.core/nonblank-string:
  (spec-tools.core/spec
   {:spec
    (clojure.spec.alpha/and
     clojure.core/string?
     (clojure.core/complement clojure.string/blank?)),
    :type [:and [:string]],
    :leaf? true,
    :name "non-blank string",
    :json-schema/description
    "string containing something other than only whitespace",
    :json-schema/type "string"})
:sixsq.nuvla.server.resources.spec.nuvlabox-0/ssh-keys:
  (spec-tools.core/spec
   {:spec
    (clojure.spec.alpha/coll-of
     :sixsq.nuvla.server.resources.spec.core/nonblank-string
     :kind
     clojure.core/vector?),
    :name "ssh-keys",
    :type :vector,
    :json-schema/display-name "NuvlaBox SSH keys",
    :leaf? false,
    :json-schema/description
    "list of SSH keys associated with the NuvlaBox",
    :json-schema/order 33})
:sixsq.nuvla.server.resources.spec.nuvlabox-1/schema:
  (clojure.spec.alpha/merge
   (clojure.spec.alpha/keys
    :req-un
    [:sixsq.nuvla.server.resources.spec.common/acl
     :sixsq.nuvla.server.resources.spec.common/created
     :sixsq.nuvla.server.resources.spec.common/id
     :sixsq.nuvla.server.resources.spec.common/resource-type
     :sixsq.nuvla.server.resources.spec.common/updated
     :sixsq.nuvla.server.resources.spec.nuvlabox/owner
     :sixsq.nuvla.server.resources.spec.nuvlabox/version
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/refresh-interval
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/state]
    :opt-un
    [:sixsq.nuvla.server.resources.spec.common/created-by
     :sixsq.nuvla.server.resources.spec.common/description
     :sixsq.nuvla.server.resources.spec.common/name
     :sixsq.nuvla.server.resources.spec.common/operations
     :sixsq.nuvla.server.resources.spec.common/parent
     :sixsq.nuvla.server.resources.spec.common/resource-metadata
     :sixsq.nuvla.server.resources.spec.common/tags
     :sixsq.nuvla.server.resources.spec.common/updated-by
     :sixsq.nuvla.server.resources.spec.nuvlabox/credential-api-key
     :sixsq.nuvla.server.resources.spec.nuvlabox/infrastructure-service-group
     :sixsq.nuvla.server.resources.spec.nuvlabox/nuvlabox-status
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/capabilities
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/cloud-password
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/comment
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/firmware-version
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/form-factor
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/hardware-type
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/hw-revision-code
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/internal-data-gateway-endpoint
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/lan-cidr
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/location
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/login-password
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/login-username
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/manufacturer-serial-number
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/monitored
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/organization
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/os-version
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/root-password
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/ssh-keys
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/supplier
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/vm-cidr
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/vpn-server-id
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/wifi-password
     :sixsq.nuvla.server.resources.spec.nuvlabox-0/wifi-ssid])
   (clojure.spec.alpha/map-of
    #{:cloud-password :description :capabilities :root-password :tags
      :supplier :wifi-ssid :resource-metadata :parent :refresh-interval
      :hw-revision-code :updated :name :credential-api-key
      :internal-data-gateway-endpoint :monitored :created :state
      :organization :vpn-server-id :form-factor
      :manufacturer-serial-number :firmware-version :hardware-type
      :os-version :updated-by :infrastructure-service-group
      :login-password :created-by :id :comment :resource-type :vm-cidr
      :acl :operations :ssh-keys :nuvlabox-status :version :location
      :wifi-password :owner :lan-cidr :login-username}
    clojure.core/any?))

-------------------------
Detected 1 error
`

**Comment by cjdcordeiro** [comment]
this was already fixed, just waiting to be released : https://github.com/nuvla/job-engine/commit/c4245710355bfd5a6e6bdebc05522cd6efaa22de
