### ISSUE TITLE
Orphelin deployment :'(

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#53]
When we delete a NuvlaBox, what should happen for deployments that have been deployed on this box ?
When we delete an OCI Infra, what should happen for deployments that have been deployed on this infra ?

**Comment by mebster** [comment]
I think deployment should be put in a stopped state and an event created to say that the reason for stopping the deployment was the removal of the NB/IS.  This way, the deployment can be restarted on a different NB/IS and we keep the trace.
