### ISSUE TITLE
versioning policy

### ISSUE THREAD

**Issue by loomis** [nuvla/nuvla#6]
Decide on the nuvla versioning policy:

 - Do we continue with coordinated versions between all repositories?
 - Do we allow for individual component versioning, possibly with coordinated global tagging?
 - What number(s) do we start with?

**Comment by cjdcordeiro** [comment]
one other way to look at it, is that we don't version Docker Images, but we have raw Dockerfiles instead which are built at runtime.

Just another option to consider. 

Nevertheless, I'd go with the 2 bullet above.

**Comment by loomis** [comment]
This ticket concerns more directly the versioning of the _source code_ from which the artifacts are created.  The artifact versions must be derived (deterministically) from the source code versions.  The question is really whether we continue with a single version for all components or go to multiple versions.  This directly affects how the release and deployment processes will be structured.

**Comment by konstan** [comment]
I vote for `individual component versioning` (second bullet point).

**Comment by elegoff** [comment]
I would also vote to allow for individual component versioning

**Comment by mebster** [comment]
As mentioned in slack, I think we should start from v2.

**Comment by loomis** [comment]
The decision from the versioning ticket is summarized [here](https://github.com/nuvla/nuvla/wiki/0003:-Versioning).  Please review and provide comments.

**Comment by loomis** [comment]
Final.  Closing issue.
