### ISSUE TITLE
user notification on BlackBox snapshot creation

### ISSUE THREAD

**Issue by konstan** [nuvla/nuvla#64]
BlackBox uses Nuvla `data-object` (and associated workflow https://docs.nuvla.io/nuvla/advanced-usage/manage-data) to upload the snapshots on S3. As of now, while running primarily on NB, the application is designed to be running independently from the NBE services. Hence, the delivery of the snapshot creation event to Nuvla is not intended to be done via NBE (Agent).

Proposed approach for event creation and alert notification.

1. Create a hook on `data-object` resource that will unconditionally produce an event of new resource creation.
2. “Streams” implementation in Nuvla has ES-to-Kafka source connector that pushes all events to `events` Kafka topic from `nuvla-events` ES index.
3. User creates a subscription to notifications on the data-object resource creation. The subscription must include a filter to select only the required `data-object`s.
4. "Streams" must consolidate the user-defined subscriptions (with filter) and the `data-object` creation events.

So, this indirect approach is because we don't have a way of defining, registering, and delivering custom events/metrics from the user space (BlackBox application).

Problems

1. Notification must contain a link to the deployment that produced the snapshot. While this can be done via either `description` or `tags` of `data-object`, the better way would be to extend the schema with `source` (?) or use `data-record` as metadata. The latter requires changes to BlackBox, the former to the api-server. Knowing the deployment we can also derive the infrastructure service and NB and put this into the notification.
2. User wants to filter the `data-object`s based on NBs or ISes - i.e. the physical locations. This is better achieved by each `data-object` having a corresponding `data-record`. Or radically, extending `data-object` to contain metadata a-la `data-record` way.

Needs discussion.

**Comment by mebster** [comment]
> So, this indirect approach is because we don't have a way of defining, registering, and delivering custom events/metrics from the user space (BlackBox application).

Would addressing this issue not be more generic and reusable by other apps?

**Comment by konstan** [comment]
Yes, it would and it should be the goal.  Here is how I see this.

1. First, we need a schema for the metrics/events. The accompanying task is a generalization of the event/metric schema as proposed here https://github.com/nuvla/api-server/issues/435. I derived it from Prometheus and collectd. We can fully adopt an existing one as well.
2. Then, we need to define and implement a policy for the metrcis/events rates and their persistence. Can be combined with payment. IMO, we shouldn't use our current system space events. 
3. A separate micro-service implementing the resource for handling the metrics/events (from 2.) must be created. For the persistence it can be Kafka. I.e. see this https://github.com/nuvla/nuvla/wiki/Metrics-data-storage,-processing,-sharing,-and-visualisation
4. Document the API and augment `nuvla-api` with the metrics/events creation/publication.
5. Users would then be subscribing to the events/metrics from that pool behind 3.

This is much more work than just what is proposed initially, but I'm happy to engage and do it the "right way" though if agreed.

**Comment by konstan** [comment]
|#|task|estimate|
|--|---|---|
| 1. | schema for metrics/events | 1 day |
| 2. | discope at this stage | 0 day |
| 3. | MS for HTTP->Kafka | 2 days |
| 4. | `nuvla-api` and docu | 2 days |
| 5. | stream processing  | 2 days |
| 6. | UI  | 1 day |
|  | total:  | 8 days |

About two weeks.

Then, 1 day to update BlackBox to start using the above event publication method.

Convenience for the users would be for us to have the publisher implementation (based on 4.) and inject a sidecar container running alongside the user's one. The user would only write a file in a predefined location and schema, e.g. (json or jaml):
```
name: BB event
message: new BB event created
resource: data-object/1-2-3-4-5
```
The schema is to be defined. The sidecar has all the information to do the heavy lifting.

**Comment by schaubl** [comment]
Closing as Done (but differently)
