### ISSUE TITLE
Notify customer about coupon expiry date

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#78]
AS A user with a coupon applied on his subscription

I NEED TO be notified when my coupon is about to expire

SO THAT I can request a new coupon or to add a payment method

# Questions

How much coupon expiring email will user receive [**1 email 1 week before expiration**/other]

What should happen when a coupon expire? [**Nothing (Subscription move automatically to active done by Stripe)**/We cancel subscription/other]

# [api-server](https://github.com/nuvla/api-server)

Word email to notify the coupon will expire.

Word email to notify that coupon expired.

# [api-server-private](https://github.com/nuvla/api-server-private)

Action to be done? Nothing or cancel subscription? new action on customer similar to `trial-end`
Trial resource with action regenerate. That return subscription with trial ending.
Expiring-Coupon resource with action regenerate. That return coupon ending with the customer info that uses it. And should be notified.

Add a resource similar to trial to get customer with coupon that will expire.

(This resource will be later moved to a call done `/api/hook/expiring-coupon available for admin later.` or we can do it directly)

# [job-engine](https://github.com/nuvla/job-engine)

Distributor for each customer with coupon that will expire
Executor that will call operation on customer

**Comment by FabianMk** [comment]
Discussed topics:
* if a customer enters a coupon we set his subscription to active (ending his trial)
* 1 week before expiry email. Tell him that he will get charged, with a soft reminder about payment method
* on expiry we send another email to remind him. his subscription will stay active and no resources will be frozen.
* send email to account email of stripe. this should also be done in the trail automation, as groups don't have an email.
* Ideally we also send an email to the billing email address and the cc email (set in stripe)
* ui currently does not show expiry date

**Comment by 0xbase12** [comment]
Email-cc not supported in api : https://github.com/stripe/stripe-dotnet/issues/1641

**Comment by 0xbase12** [comment]
### Listing expiring coupon
This is not possible to be achieved without workarounds (using undocumented feature).
No webhooks is implemented to notify about expiring coupon.
The only way we found to do that is list coupons. Filter out valid ones. List customers and filter on coupon id. This filter is not documented in stripe API.
