### ISSUE TITLE
 Allow customer to use Nuvla when he has credit on his account

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#79]
AS A customer with credits on my account

I NEED TO be able to create deployment and nuvlabox

SO THAT my credit is being consumed

# Questions

Do we want to cancel the subscription of a customer with credit on his account? [yes/**no**]

Do we want to notify the customer about trial ending? [**yes**/no]

Do we want to notify the customer about trial ended? [**yes**/no]

# [api-server-private](https://github.com/nuvla/api-server-private)

Can be credit considered as a payment method. This will make the existing code reusable.

Check the working of notify trial end email if is okey with this case.

The credit will be added in Stripe dashboard. No need to make it through Nuvla

Update `customer-info` operation to return if a user has some credit. The `:credit` field is new.

```
{:fullname "Tarzan Something",
 :address
 {:street-address "Somewhere",
  :city           "Forest",
  :country        "XX",
  :postal-code    "123"},
 :coupon
 {:id                 "asdkaa",
  :name               "Some coupon name",
  :amount-off         nil,
  :currency           nil,
  :duration           "forever",
  :duration-in-months nil,
  :percent-off        100,
  :valid              true}
 :credit   {:amount   100.3
            :currency "EUR"}
}
```

# [ui](https://github.com/nuvla/ui)
Display to the customer the credit he has in profile page.

**Comment by FabianMk** [comment]
Here is the result of our trusted customer story discussion:
* If a customer has credit the customer will not get trial end emails and his subscription will move to active at the end of his trial.

**Comment by FabianMk** [comment]
PRs
https://github.com/nuvla/api-server/pull/676
https://github.com/nuvla/ui/pull/820
https://github.com/nuvla/api-server-private/pull/13
