### ISSUE TITLE
 Allow admin to set trust flag on customer

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#81]
AS AN admin

I NEED TO be able to set trust flag on customer

SO THAT he will be able to add Nuvlabox and deployment even without payment methods set

# Questions

What if he forget to pay and his subscription goes to past-due or unpaid. Will he able to do actions on deployment or nuvlabox [**yes**/no] ?

Do we want to cancel the subscription of a trusted customer? [yes/**no**]

Do we want to notify the customer about trial ending? [yes/**no**]

Do we want to notify the customer about trial ended? [yes/**no**]

# [api-server-private](https://github.com/nuvla/api-server-private)

Customer resource is editable only by admin user. 
We can add an optional boolean field `trusted?` into the customer spec.
Admin can edit this flag in raw mode in UI to set it as he want.

Check the working of notify trial end email if is okey with this case.

# [api-server](https://github.com/nuvla/api-server)

This is the call that drives that a customer will be blocked (e.g. when adding a deployment)
`sixsq.nuvla.server.resources.user.utils/customer-has-active-subscription?`

**Comment by FabianMk** [comment]
Here is the result of our trusted customer story discussion:
* We manage our customers in stripe. Invoices can be marked as void or uncollectible to keep a customer active. No separate flag in our backend is needed for now.
* If a customer has credit the customer will not get trial end emails and his subscription will move to active at the end of his trial.
* If a customer enters a coupon his trial will be ended and the subscription activated.

**Comment by 0xbase12** [comment]
Context: We got some users that create nuvla accounts but they will use only groups to deploy NuvlaEdges/deployment. We don't want to bother these users with emails about end of trial on their accounts or let them create NuvlaEdge on their own account and get them invoiced personnaly.  

The best solution is that these users should not start trial when they create their account. In this case users will not be linked to customers. Creation of NuvlaEdges will be rejected under their account and they will be able to switch to a group linked to a customer to be able to deploy resources.
