### ISSUE TITLE
Allow to see nested subgroups resources

### ISSUE THREAD

**Issue by 0xbase12** [nuvla/nuvla#93]
AS A user that is part of group 1 with subgroup 1.1

I CAN switch to group 1 with an option to see all resources of nested subgroups

IN ORDER TO see aggregated resources of group 1 and nested groups

**Comment by 0xbase12** [comment]
Note: User will behave as the group he switched to. 
(e.g. when adding a NuvlaEdge, he will create it with the group he switched to as owner).

He will be also able to do actions on all visible resources if the acl allows it. In example decommission a NuvlaEdge for a subgroup.

**Comment by mebster** [comment]
We need to be able to know which user has performed what action on any given resource, such that we can have a nominative audit trail.  This could be via events.  But I think we should know from a resource (e.g. NuvlaEdge) who the user was that created the resource and last updated it.

**Comment by 0xbase12** [comment]
> We need to be able to know which user has performed what action on any given resource, such that we can have a nominative audit trail. This could be via events. But I think we should know from a resource (e.g. NuvlaEdge) who the user was that created the resource and last updated it.

The attribute created-by and updated-by are always pointing to the user-id of the logged in user. User-id doesn't change when user do a  switch-group.
